# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - id: tailpipe-darwin-amd64
    binary: "{{ .ProjectName }}.plugin"
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -tags=netgo
    ldflags:
      - -s -w

  - id: tailpipe-darwin-arm64
    binary: "{{ .ProjectName }}.plugin"
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    flags:
      - -tags=netgo
    ldflags:
      - -s -w

  - id: tailpipe-linux-arm64
    binary: "{{ .ProjectName }}.plugin"
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    flags:
      - -tags=netgo
    ldflags:
      - -s -w

  - id: tailpipe-linux-amd64
    binary: "{{ .ProjectName }}.plugin"
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    flags:
      - -tags=netgo
    ldflags:
      - -s -w

archives:
  - format: gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"